### ISSUE TITLE
Chat 2: Dalamud Crash upon party invite via Chat2 context menu

### ISSUE THREAD

**Issue by jasinkare** [ascclemens/plugin-issues#10]
3 crash logs included, reproduces every time on my machine.

Right clicking on player name, select invite to party, same world option, crash.

Does not occur with different world option, that one functions properly.

[dalamud_appcrash_20220824_205913_905_20840.log](https://github.com/ascclemens/plugin-issues/files/9420959/dalamud_appcrash_20220824_205913_905_20840.log)
[dalamud_appcrash_20220824_214642_640_21648.log](https://github.com/ascclemens/plugin-issues/files/9420960/dalamud_appcrash_20220824_214642_640_21648.log)
[dalamud_appcrash_20220824_215308_718_9068.log](https://github.com/ascclemens/plugin-issues/files/9420961/dalamud_appcrash_20220824_215308_718_9068.log)

I am bad about checking git, if you need more info or if I should post in goats discord please reach out on discord @ Jassss#6969

**Comment by Cerberux19** [comment]
Having the exact same issue since recent update as of 930am EST 8/25/2022

**Comment by Shiichibukai** [comment]
Can confirm, this causes an instant crash. gh wont let me upload my log file here.

**Comment by ascclemens** [comment]
(Hopefully) Fixed in latest release. Re-open if not.

**Comment by jasinkare** [comment]
Appears to be fixed, thank you ♥
