### ISSUE TITLE
Chat2 Pop out tabs - Issue with re-docking

### ISSUE THREAD

**Issue by Cerberux19** [ascclemens/plugin-issues#11]
Not sure if isolated to just Chat2, as I have not been able to replicate it on any other plugin, but when I pop out a chat tab, and try to re-dock it, I receive an endless loop of all of Dalamud flashing like crazy and am unable to do anything with Dalamud at all. Disabled Chat2 and everything returned to normal.

**Comment by ascclemens** [comment]
Then don't do that.

**Comment by Cerberux19** [comment]
I literally can't do anything with chat2, and it is a function of the plugin to pop tabs out to separate windows. When trying to put it back, it borks the plugin completely.

**Comment by Cerberux19** [comment]
https://user-images.githubusercontent.com/112096274/186811505-cc19dd26-1347-4302-8de9-775175ba1f5e.mp4

**Comment by Cerberux19** [comment]
This was not an issue prior to 6.2. Other plugins dock together just fine, for instance, combining Penumbra and Glamourer tabs do not cause any issues. Seems to be isolated to just Chat2

**Comment by Cerberux19** [comment]
Turned off window docking in Dalamud, closed popped out tab, everything back to normal. It is still an odd issue that Chat2 is the only plugin that is behaving that way when dragging windows together. It worked fine that way prior to the latest update. I could take a popped out tab, drag it back to the main Chat2 window and it would re-attach without issue.
