### ISSUE TITLE
Glamaholic: Glamour Dresser warning stuck

### ISSUE THREAD

**Issue by NotNite** [ascclemens/plugin-issues#15]
Reported by `Arein#1594` and `Satoshi#7422`. Out of date opcode/sig?

User also reported "saved plates are not applying" but I don't use this plugin, only installed to test, so fuck if I know what that means LMFAO

**Comment by ascclemens** [comment]
Yeah the whole plugin just doesn't work right now. Doesn't crash but is mostly not functional.
