### ISSUE TITLE
Chat2/ExtraChat Filters

### ISSUE THREAD

**Issue by KhaozFrost** [ascclemens/plugin-issues#17]
![image](https://user-images.githubusercontent.com/15788954/187044434-fb1682e1-950f-4f48-95cd-3ac79c0c27d2.png)
few things; there are no 'input channels' for extrachat. The bubble doesn't allow you to select them either. 
and I tested with a channel setup 
![image](https://user-images.githubusercontent.com/15788954/187044470-8082128e-a3fe-4970-8619-b3e437b05095.png)
and used the command /ecl1 test to see if it would appear in the new tab
![image](https://user-images.githubusercontent.com/15788954/187044489-a6019e29-e507-4d88-968f-2e2d99609c7a.png)
and it didnt do anything.

**Comment by KhaozFrost** [comment]
![image](https://user-images.githubusercontent.com/15788954/187044516-39e9aa71-e841-48dc-8593-e2ab179e6c60.png)
![image](https://user-images.githubusercontent.com/15788954/187044532-1fed38ed-0655-4595-9b0d-c83abebd9750.png)
![image](https://user-images.githubusercontent.com/15788954/187044544-9d712781-6a53-4112-924f-52793ab485ee.png)

**Comment by ascclemens** [comment]
A filter is not an input channel, so the latest update obviously does not add that functionality.

It looks like for now you need to enable System Messages as well.

**Comment by ascclemens** [comment]
No longer need to include System Messages.
