### ISSUE TITLE
Mastercraft food req. in macro causing craft to not work

### ISSUE THREAD

**Issue by Electrized** [ascclemens/plugin-issues#18]
Craft queues, but crafts nothing (doesn't even open craft menu nor apply food), seemingly to do with HQ food?

Image below showing no food & nq food working;

![image](https://user-images.githubusercontent.com/29844497/187096503-b2c17e10-7ad5-4119-9e3d-8523af1e3bb7.png)

**Comment by ascclemens** [comment]
I'll look into it. Stuff changed after 6.2 that made it stop working.

**Comment by ascclemens** [comment]
In the chat log it probably posted a message, or in /xllog

**Comment by shinyrukii** [comment]
![image](https://user-images.githubusercontent.com/21201885/187096936-8025bb30-7ddc-46d0-bc29-7ed88764b5e1.png)
is being shown in the /xllog when starting a craft with HQ food.

**Comment by Electrized** [comment]
Spams this indefinitely until cancel / pause, have the correct food in inventory etc etc
![image](https://user-images.githubusercontent.com/29844497/187096978-1b5b692f-60d5-4a26-8f55-f9aee9a0250e.png)

**Comment by ascclemens** [comment]
I'll look after this ex farm, thanks!

**Comment by ascclemens** [comment]
Fixed in 1.0.1.
