### ISSUE TITLE
Mastercraft - Specialist action "Heart and Soul" doesn't activate

### ISSUE THREAD

**Issue by Mr-Ouija** [ascclemens/plugin-issues#19]
Heart and Soul gets picked up in the macro import, shows icon in rotation, but doesn't fire when it's supposed to, then pauses. For ALC at least, can't say for the others atm.

Turned logging on, but don't seem to be getting a message in the chat log. /xllog pretty much shows the following:

```
[INF] [Mastercraft] step 5: -1000
[INF] [Mastercraft] step 5: -1 (spammed until activated manually and finished)
[INF] [Mastercraft] step 5: -100
[INF] [Mastercraft] step 5: -100
[INF] [Mastercraft] job finished
```

Great job though, super fast! Thanks for all your hard work!

**Comment by ascclemens** [comment]
Thanks, I'll look into it tonight or tomorrow!

**Comment by ascclemens** [comment]
Try 1.0.4 and let me know.

**Comment by Mr-Ouija** [comment]
Working fine now. Old one stalled, but newly imported ones shouldn't have any issue. Tested on another class too and seems to be all good.

Thanks again!
