### ISSUE TITLE
Tourist

### ISSUE THREAD

**Issue by KMorriganeL** [ascclemens/plugin-issues#23]
Tourist doesn't work since the latest release. Could you repair it, please ?

**Comment by ascclemens** [comment]
Not my fault. Dalamud issue. When they fix their build system, I will release the fixed version.

**Comment by KMorriganeL** [comment]
Oh, thanks a lot for the time spent to  explain to me this detail. So, I'll wait for the update cause I like this pluggin a lot. 

Rgds

⁣Télécharger BlueMail pour Android ​

Le 10 sept. 2022 à 18:01, à 18:01, Anna Clemens ***@***.***> a écrit:

**Comment by ascclemens** [comment]
It's already updated and available.

**Comment by KMorriganeL** [comment]
Great, thanks a lot! 

⁣Télécharger BlueMail pour Android ​

Le 12 sept. 2022 à 09:19, à 09:19, Anna Clemens ***@***.***> a écrit:
