### ISSUE TITLE
Chat2: Player names when they speak in smushed, strange symbols, /p command getting eaten constantly

### ISSUE THREAD

**Issue by propkitty** [ascclemens/plugin-issues#26]
I'm having two separate issues that are becoming quite frustrating. One is that I'm getting player names being smushed in together with the closing bracket on their chat message as well as strange symbols popping up. See below:

![image](https://user-images.githubusercontent.com/14895964/192028164-4059874c-a48b-4af1-a6a8-735ec6665f41.png)

The above image also has an example of that - I know the strange symbol at the end of the bottom tell is supposed to be the alt+3 heart symbol but instead, I'm getting that. The name-smushing is only happening to players who have I on my friend's list and have them in a group, thus a symbol by their name. This can happen in FC chat, tells.. anywhere the player has a symbol by their name.

I do not have any custom anything set other than I've made the font-size smaller.

The other issue is when I'm typing /p to reply in party chat, the / always appears but about 25% of the time, it's opening up the P menu (Actions and Traits) instead of continuing to type in the chat bar. 

Neither of these happened previously but seems to be from a somewhat recent update - either of Dalmund as a whole or the plugin, not sure which.

**Comment by propkitty** [comment]
Someone was kind enough to give me an assist for this in the Discord - while the /p is still an issue even with the fix, I had to go into Dalmund and click 'Use AXIS fonts as default Dalamud Font' in order to repair this issue. It's strange as I have not had this issue previously, but it did solve the smushy names/broken symbols at least! Now if only I could safely type /p! :)

**Comment by ascclemens** [comment]
This is not a bug. The font you had chosen did not have those particular symbols in it, so they showed up as the "missing symbol" glyph!

**Comment by propkitty** [comment]
What about the second issue? Would you rather I have another issue created for it?

**Comment by ascclemens** [comment]
Can't reproduce. I'll keep an eye out for it.

**Comment by propkitty** [comment]
I could screen record perhaps to show you it in action, if that would help?

**Comment by ascclemens** [comment]
Oh, I actually misread the second issue, and I have had that happen, but I'm not sure why. It's a minor bug, so it's not high on my list of priorities. I know about it, though, so when I spend time on Chat 2 I may be able to fix it.

**Comment by propkitty** [comment]
Ah, thank you very kindly! It's not massively a bug, just frustrating when you're trying to rapid-type during combat to your party and it keeps doing that! <3
