### ISSUE TITLE
ExtraChat: Plugin not working with new NA datacenter servers

### ISSUE THREAD

**Issue by Pyresque** [ascclemens/plugin-issues#34]
Since the addition of the new Dynamis datacenter, I am unable to authenticate a character whose home server is now within it. With an existing character that was transferred, I can still speak on already created linkshells, but my character is still listed by their old name and server, and has lost any admin privileges. The character is also unable to leave existing linkshells, making it impossible to create a new account--which wouldn't work anyway since authentication is failing for anyone on the Dynamis DC.

People with the same issues have reported it in the Anna Plugins thread on the goat place Discord.

**Comment by ascclemens** [comment]
> People with the same issues have reported it in the Anna Plugins thread on the goat place Discord.

Not only do I not check there, I didn't even know it existed. This is probably a bug with the new worlds, yeah. I'll have to fix that. I'll look at it tonight.

**Comment by ascclemens** [comment]
Pushed an update. Let me know if it's fixed!

**Comment by Pyresque** [comment]
Hi! So sorry, I thought the fact they had a channel up for your plugins meant that you were there and I just wanted to direct you to a place with more detailed reports in case you hadn't seen them. Bit odd they have it set up if you're not there, but oh well. LOL

Happy to say the latest update did fix it for me! Plugin shows my new name and server and I have admin permissions on my linkshells again. Thank you so much for your work on this plugin, it's a godsend being able to still talk with my friends after moving DCs!
