### ISSUE TITLE
Interupting typing

### ISSUE THREAD

**Issue by McJamja93** [ascclemens/plugin-issues#59]
Hey i seem to have this issue with Chat2 where if im typing and then combat begins it will automatically leave the chat window so im no longer typing a message in the box but instead rapidly opening every interface bound to a key. I have tried reverting back to the vanilla chatbox by itself as well as using Tidy Chat plugin and havent had the issue. Is this an issue that anyone else is having or have i got something somewhere thats causing this? Thanks in advance.

**Comment by ascclemens** [comment]
Any plugin window that opens will steal focus from Chat 2. Nothing I can do about that.
