### ISSUE TITLE
NoSoliciting is flagging my own shouts as "Free Company Ads"

### ISSUE THREAD

**Issue by rvaidya** [ascclemens/plugin-issues#6]
NoSoliciting shouldn't apply any filters on your own shouts.

Shout category: "Free Company ads"
Shout text: "dis my new home now, hello fellow Goblins"

I am in a large FC that does advertise frequently, if that helps narrow things down.  I've never advertised the FC or any FC myself.

**Comment by ascclemens** [comment]
Use the built-in reporting feature for this.
