### ISSUE TITLE
Chat 2 Chat Focus Toggle

### ISSUE THREAD

**Issue by eksynn** [ascclemens/plugin-issues#61]
i understand chat 2 is meant to be a "complete replacer" to the original chat UI (OCUI), but as much as I love 99% of the features of Chat 2, I still greatly prefer how the OCUI used to look. I've no real need for more tabs than the original one provides.. at least not yet. not while I still figure things out and focus on other things.
so, I offer two suggestions on how to resolve this, both of which can be done together, without one replacing the other:
• first, add a button to copy the tabs and channels from the OCUI to Chat 2. copying all of the channels over to Chat 2 is such a pain that I "haven't got round to it yet".
• lastly and probably easiest to do, please add a check box to allow the focus to go to the OCUI instead of chat 2 as a toggle in the settings (with the default leading to Chat 2 so as not to affect anyone who updates to it), allowing the user to use the best features of chat 2 with the OCUI

**Comment by ascclemens** [comment]
no

**Comment by eksynn** [comment]
> no

neither one? how come?

**Comment by ascclemens** [comment]
I do not accept feature requests.
