### ISSUE TITLE
6.4 Glamaholic: Try On Feature Only Applies One Slot

### ISSUE THREAD

**Issue by R-enn** [ascclemens/plugin-issues#65]
The "Try On" feature, from either the glamaholic menu, or from examining a character only manages to apply one item, if any.
Saving the outfit does manage to grab all of the item slots, so that piece of functionality still works.

![glamaholic_try_on_bug](https://github.com/ascclemens/plugin-issues/assets/10716596/f32343c5-e548-42e7-be18-fd6b029af37b)
![glamaholic_try_on_bug_main_menu](https://github.com/ascclemens/plugin-issues/assets/10716596/f8ece19e-9891-4d7e-b3ee-b36516747ca8)

**Comment by ascclemens** [comment]
dalamud for 6.4 isn't even officially released ;-;

**Comment by R-enn** [comment]
Ah, sorry. I was reporting it as part of the closed beta, and was told it'd be better to file the issue on the github repo.
