### ISSUE TITLE
Chat2 - Linkshells not appearing in channel select

### ISSUE THREAD

**Issue by Alixandria** [ascclemens/plugin-issues#9]
Just updated to v1.17.5.0 and linkshells (both cross-world, and not) aren't appearing in the channel select. Have tried relogging and reinstalling to see if it was some weird jank, still hasn't appeared.

**Comment by Lockehart** [comment]
to add to this, the alt+C and alt+L shortcuts to cycle through them also are broken

**Comment by Shiichibukai** [comment]
System error pops up saying /linkshell2 is not available, the command. Also yes, keybinds arent working to swap between linkshells/cwls's. Selection also broken.

**Comment by ascclemens** [comment]
Fixed in latest release.
